HEADER = 0x6767
LOGIN = 0x01
GPS = 0x02
HEARTBEAT = 0x03
ALARM = 0x04
TERMINAL_STATE = 0x05
OBD = 0x07
DOWNLINK_COMMAND = 0x80
DEFAULT_HEADER = 0x6767

EELINK = 'eelink'
QUECLINK = 'queclink'
ATRACK = 'atrack'
SQUAREL = 'squarel'
CANGO = 'cango'

DEVICE_TYPES = (EELINK, QUECLINK, ATRACK, SQUAREL, CANGO)

DTC_CODE_SPLITTER = ','